### PR TITLE
pep 8 and new tests.

### PR DESCRIPTION
**Pull request by fmaussion**
Some cosmetic changes to the examples, a couple of new tests

### CODE REVIEW

**Comment by fmaussion** [comment]
@ryancox if your reading this: the last changes you made to travis may be obsolete: I added some tests in order to check if the examples do run without error

**Comment by fmaussion** [comment]
OK I've seen you just reverted. Anyway, I'll wait to know what you're up to before I merge this one

**Comment by ryancox** [comment]
Go ahead! sorry to stomp on that. After this gets merged I'd like to add some integration tests in travis that run the examples and compare with known good files. I noticed it might be slightly tricky since python 2 and 3 end up generating different URls ... probably dict order traversals are not the same.

**Comment by fmaussion** [comment]
Alright, sounds good. Yes, the url's are not guaranteed to be always same (also for DecoratedMaps with address markers). Using OrderedDicts could be an option, I guess.

OK so I now merge this one and wait for your changes.

**Pull request merged**
