### PR TITLE
Remove six dep

### LINKED ISSUE #42: six dependency imported implicitly in setup.py
# Implicit import of six dependency in setup.py causes install failure

Hi there; I encountered an issue installing motionless on a fresh virtualenv for python 3.7.0

Great package by the way! Has been very useful!

## Error message
```
user@localhost:~/some_dir $ pip install motionless
Collecting motionless
  Using cached https://files.pythonhosted.org/packages/.../motionless-1.3.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/.../motionless/setup.py", line 3, in <module>
        from motionless import __version__
      File "/.../motionless/motionless.py", line 2, in <module>
        from six.moves.urllib.parse import quote, urlparse
    ModuleNotFoundError: No module named 'six'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /.../motionless/
```

## Cause

The [setup.py](https://github.com/ryancox/motionless/blob/master/setup.py) script imports the version from [motionless.py](https://github.com/ryancox/motionless/blob/master/motionless.py) at [line #3](https://github.com/ryancox/motionless/blob/master/setup.py#L3).

This import implicitly invokes the import of the six module in [motionless.py](https://github.com/ryancox/motionless/blob/master/motionless.py) at [line #5](https://github.com/ryancox/motionless/blob/master/motionless.py#L5). 

If six is not yet installed, installing via setuptools/pip will fail

## Fix

Maybe move the version out into its own file?

### PR DESCRIPTION
**Pull request by JMSwag**
Fixes #42

### CODE REVIEW

**Comment by fmaussion** [comment]
Thanks!

**Comment by JMSwag** [comment]
@fmaussion NP! A minor release would be awesome!

**Comment by fmaussion** [comment]
> A minor release would be awesome!

I tagged it here: https://github.com/ryancox/motionless/releases/tag/v1.3.3

But I don't have credentials to publish it on PyPI: @ryancox , could you make the release (or add me as package maintainer on PyPI?) Thanks!

**Comment by chingc** [comment]
Thanks for fixing this!  Looking forward to this to appear on PyPI.

**Pull request merged**
