### PR TITLE
Update motionless.py

### PR DESCRIPTION
**Pull request by evstratbg**
fix pathes generation

### CODE REVIEW

**Comment by fmaussion** [comment]
Thanks for your PR, and sorry for my late reply due to the summer break. 

Could you clarify a bit what problem this PR is solving? (I'd like to add a regression test for it)

**Comment by evstratbg** [comment]
ye
there are some changes as I can see. Now, there is no encoding at all, adding a path on a gmap, just joining using '|'

&path=55.408611,37.906111|41.610278,41.599694&

**Comment by fmaussion** [comment]
Right now you're removing encoding as a whole, but encoding is considered a useful feature by many.

If you want to not use encoding, one could possibly add a mechanism for it, maybe via kwarg or something (TBD)

**Comment by evstratbg** [comment]
I haven't found if _polyencode with GPolyEncoder is used in code except for pathes

**Comment by fmaussion** [comment]
> I haven't found if _polyencode with GPolyEncoder is used in code except for pathes

Yes, the default **is** to encode paths and it should remain like this. Your PR, as it stands, changes this default behaviour and we don't want this.

In order to solve your problem I suggest to give the user an option to *disable* encoding if wanted. A recent PR (https://github.com/ryancox/motionless/pull/27) already added some control on the precision at which the paths should be encoded, we could use the same keyword to disable encoding as a whole, for example if we say ``simplify_threshold_meters = None`` would be equivalent to saying "don't do encoding".

**Comment by evstratbg** [comment]
Ok, i got your idea
But I still don't understand why we should not delete encoding? It isn't working

**Comment by fmaussion** [comment]
Can you specify what "it doesn't work" mean, ideally with an example? I'm not using it myself but I know that people are using it.

 Cc @riggsd

**Comment by evstratbg** [comment]
[mtnlss.zip](https://github.com/ryancox/motionless/files/1280704/mtnlss.zip)
Here is a zip arch. Just run motionless_test using python3.x, with motionless installed. Archive contains the updated version of a lib

**Comment by fmaussion** [comment]
Using your (simplified) example on the latest master I don't see any problem:

```python
from motionless import DecoratedMap, LatLonMarker

lats = [40, 60]
lons = [38, 38]
dmap = DecoratedMap(scale=2, maptype='terrain', zoom=3)
dmap.add_marker(LatLonMarker(lat=lats[0], lon=lons[0], color='red'))
dmap.add_marker(LatLonMarker(lat=lats[-1], lon=lons[-1], color='red'))
for lon, lat in zip(lons, lats):
    dmap.add_path_latlon(lat, lon)
print(dmap.generate_url())
```


And even playing a bit:

```python

lats = [40, 45, 50, 55, 60]
lons = [38, 43, 33, 43, 38]

dmap = DecoratedMap(scale=2, maptype='terrain', zoom=3)
dmap.add_marker(LatLonMarker(lat=lats[0], lon=lons[0], color='red'))
dmap.add_marker(LatLonMarker(lat=lats[-1], lon=lons[-1], color='red'))
for lon, lat in zip(lons, lats):
    dmap.add_path_latlon(lat, lon)
print(dmap.generate_url())
```


This all looks good to me...

**Comment by evstratbg** [comment]
I'm very sorry, looks like PyCharm does the magic, clicking on url from tab
Thank you for patience and your time!

**Pull request closed without merging**
