### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tcyrus**
@ryancox, Changed PNG Badge to SVG and Added Python Code Blocks to README.md

### CODE REVIEW

**Comment by fmaussion** [comment]
Hi @tcyrus , sorry it took me so long to get back to you. Since https://github.com/ryancox/motionless/pull/14 your PR now has conflicts with master. Would you mind fetching the latest master and see how to take care of the conflicts? Thanks a lot!

**Comment by tcyrus** [comment]
Hi @fmaussion, I resolved the merge conflicts with master.

**Comment by tcyrus** [comment]
Any reason this wasn't merged

**Comment by fmaussion** [comment]
Please squash your commits into one, it is silly to use two commits to change a badge.

Just out of curiosity: what's your motivation for all those readme commits?

**Comment by fmaussion** [comment]
closed via https://github.com/ryancox/motionless/pull/18

**Pull request closed without merging**
