### PR TITLE
Support for map styling and custom maker icons

### PR DESCRIPTION
**Pull request by seb-b**
Hi, I've been using motionless for a project and needed a few new features so I thought I might as well add them in. The two I needed were:
- [custom markers icons](
https://developers.google.com/maps/documentation/static-maps/intro#CustomIcons)
- [styling rules for maps] (https://developers.google.com/maps/documentation/static-maps/intro#StyledMaps)

I also added a few lines to the README to document how to create definitions for the styling rules.
I forked from @fmaussion's pull request because the project I needed this for was python3. I've ran into no problems using that branch.

### CODE REVIEW

**Comment by fmaussion** [comment]
Thanks a lot! I'll get back to this and merge it no later than monday. Travis is failing with ``AttributeError: 'module' object has no attribute 'test_motionless'``, any idea whats going on?

**Comment by seb-b** [comment]
No idea sorry :-/ I don't have much experience with travis. The tests pass fine locally for me on python 2.7 and 3.4.

**Comment by fmaussion** [comment]
I'm also not entirely sure about what's going on, but we'll try something else. Could you please make a new change to `.travis.yml` and change the line:

```
 - python setup.py test
```

to:

```
 - pip install -e .
```
? Thanks!

**Comment by seb-b** [comment]
That seemed to work, cheers. I also added a test to keep coveralls happy.

**Comment by fmaussion** [comment]
Perfect, thanks! I'll merge this now and make further modifs (for tests and doc) in the upcoming days. After those I guess that I'll ask Ryan to make a new pypi realease.

**Comment by ryancox** [comment]
@fmaussion sounds good. be sure and create a 1.3 tag when everything is merged and tested. Thanks!

**Pull request merged**
