### PR TITLE
Py3 support

### PR DESCRIPTION
**Pull request by fmaussion**
Code should now be py2 and py3 compatible. New dependency: six

The demo `earthquakes.py` is broken, but this is not due to my changes. 

I find motionless very useful, thanks! With a bit more effort it should be possible to increase test coverage and modernize the doc and install scripts, I might come back to this when I have more time...

### CODE REVIEW

**Comment by ryancox** [comment]
@fmaussion Added you as a repo collaborator. Feel free to test and merge in this PR yourself as well as any others. Thanks for your help!

**Comment by fmaussion** [comment]
Alright thanks. I'll try to spend some time on this soon.

**Comment by yoavram** [comment]
Just wanted to add that I used the py3-support branch by @fmaussion and it works great.

**Comment by fmaussion** [comment]
Improved by: https://github.com/ryancox/motionless/pull/14

**Pull request closed without merging**
